debug: false

# 授权 ID 如果ID为空，插件依旧正常使用，但是会有较为大量的提示消息
verifyId: ""

#
# 数据库设置，选择你需要使用的数据储存方式，sqlite,mysql
# 默认: sqlite
data_storage:
  use_type: sqlite
  mysql:
    host: '127.0.0.1'
    port: 3306
    database: 'server_mail'
    username: 'root'
    password: '123456'
    params: '?autoReconnect=true&useSSL=false'
  hikari_settings:
    maximum_pool_size: 10
    minimum_idle: 10
    maximum_lifetime: 1800000
    keepalive_time: 0
    connection_timeout: 5000
redis:
  # 是否启用 Redis 用作跨服发送，如果不启用，默认使用插件通道。
  use: false
  # 服务器 IP
  host: 127.0.0.1
  # 服务器 端口
  port: 6379
  # 密码，若无留空
  password:
  # 是否使用 ssl 加密
  ssl: false

smtp:
  use: false
  # smtp 连接参数，可以自定义其它参数以此适应不同smtp服务商
  map:
    # 发件账号
    account: '****r@163.com'
    # smtp服务器授权码
    password: '*********'
    # 发件人信息
    personal: 'NeonMail-Premium'
    # 邮件标题
    subjects: 'NeonMail-收件提醒'
    # 自定义连接参数
    # 如果你所使用的smtp在连接时遇到问题，可以尝试调整、添加自定义参数以适应。
    # 参数使用 . 的地方请替换为 _
    mail_smtp_auth: "true"
    mail_smtp_host: 'smtp.163.com'
    mail_smtp_port: '25'
    mail_transport_protocol: 'smtp'
    mail_smtp_timeout: '25000'
    #mail_smtp_starttls_enable: "true"

  # 这里可以定义忽略的通知
  filter:
    # 以下发送者不会通过 smtp 通知
    sender:
      - '系统'
      - '某某玩家'
    # 保护以下标题的邮件不会通过 smtp 通知
    title:
      - '？？？'


# 邮件过期时间，如果永不过期 = -1
expiryTimer: 2d

# 物品邮件 物品预览使用 lore 展示 (只限 1.17+)
useBundle: false

# 附件信息展示方法
# 请注意，分割务必使用 ; 符号
mailDisAppend: "§f{0} §7* §f{1} ;"

# 特殊的语言文件，在带有过多物品时显示
mailDisMiss: "§7剩余 §6{0} §7项未显示..."


# 自定义翻译
# 部分短词的翻译，以适应不同的语言环境
typeTranslate:
  混合邮件: "&e混合类型"
  # 混合邮件: "&e Normal"
  纯文本: "&f纯文本"
  # 纯文本: "&f text"
  已提取: "&a已领取"
  # 已提取: "&a Acquired"
  纯文本已读: "&a纯文本已读"
  # 纯文本已读: "&a TextAcquired"
  未提取: "&f未领取"
  # 未提取: "&f NotObtained"
  系统: "&9系统"
  # 系统: "&9 system"
  无: "&9无"
  # 无: "&9 Not"


# 对玩家输入的字符串进行匹配检查
# 放置一部分注入，以及敏感词, 建议以正则表达式为主，以提供检查性能
# 支持正则表达式
inputCheck:
  # 本地词库
  local:
    - "腐竹傻逼"
    - "傻逼"
    - '[\s\S]*中国[\s\S]*'
  # 云词库
  cloud:
  # - "https://raw.githubusercontent.com/Yurinann/Filter-Thesaurus-Cloud/main/database.json"
# 云词库需要的 JSON 格式
# 或者通过API自行注册新正则
#  {
#    "words": [
#      "fuck",
#      "fucku",
#      "nmsl"
#    ]
#  }